language: cpp
os:
  - linux
branches:
  only:
    - master
compiler:
  - gcc
  - clang
sudo: false
addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - qtdeclarative5-dev
script:
  - qmake
  - make

